### ISSUE TITLE
Share on Instagram is not working. 

### ISSUE THREAD

**Issue by darpanvithani** [vstirbu/InstagramPlugin#70]
**I am passing object with byte code of data and some static caption info. below is output when I run $cordovaInstagram.share($scope.image.data, $scope.image.caption).then(function() {}, function(err) { }); Also I have tried without caption, still not working.**

Below are the error logs.

TypeError: Cannot read property 'slice' of undefined
at Object.Plugin.share (http://192.168.51.2:8100/plugins/cordova-instagram-plugin/www/CDVInstagramPlugin.js:93:18)
at Object.share (http://192.168.51.2:8100/lib/ngCordova/dist/ng-cordova.js:4653:17)
at Scope.$scope.shareViaInstagram (http://192.168.51.2:8100/js/controllers.js:703:23)
at fn (eval at (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:27638:15), :4:242)
at http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:65427:9
at Scope.$eval (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:30395:28)
at Scope.$apply (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:30495:25)
at HTMLAnchorElement. (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:65426:13)
at HTMLAnchorElement.n.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js:3:7537)
at HTMLAnchorElement.r.handle (https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js:3:5620)

**Comment by vstirbu** [comment]
the `canvasIdOrDataUrl` argument type is `string`. it is either the id of a canvas element or a data url similar to [canvas.toDataUrl](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).

**Comment by darpanvithani** [comment]
I am passing value like below in $scope.image.data
// "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNby
// blAAAADElEQVQImWNgoBMAAABpAAFEI8ARAAAAAElFTkSuQmCC"

is this okay? or do I need to pass something else?

**Comment by vstirbu** [comment]
that should be fine

**Comment by darpanvithani** [comment]
but its not working.

**Comment by vstirbu** [comment]
can you use that value in the [sample app](https://github.com/vstirbu/instagramplugin-example)?

**Comment by darpanvithani** [comment]
let me try once again. and caption can create any problem?
If yes, then I can try without caption.

**Comment by vstirbu** [comment]
if you use it in an ionic app via [ng-cordova](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/instagram.js), you need to pass to share an object:

```
{
   image: "yourDataUrl"
}
```

**Comment by darpanvithani** [comment]
![image](https://cloud.githubusercontent.com/assets/18464613/17855040/05aadf4a-6894-11e6-8ab4-a88401d7628f.png)

I got this kind of output.

**Comment by darpanvithani** [comment]
Hi @vstirbu  it works now.
We need to pass whole object which has a key named image and caption.
while in your tutorial and readme file you wrote like below.
$cordovaInstagram.share($scope.image.data, $scope.image.caption).then(function() {
    // Worked
  }, function(err) {
    // Didn't work
  });

here key name is data while your plugin expects image.
so now everything works fine.

**Comment by vstirbu** [comment]
ng-cordova project is not maintained by me, so there might be some mismatches. you can open an issue there so that they can update the documentation.
