### ISSUE TITLE
Failed to fetch plugin https://github.com/Visigo/CordovaClipboard.git 

### ISSUE THREAD

**Issue by codebeauty** [vstirbu/InstagramPlugin#83]
I'm trying to install InstagramPlugin but it always fails with CordovaClipboard. Maybe a connection to #82 .

`
→ ionic cordova plugin add cordova-instagram-plugin
> cordova plugin add cordova-instagram-plugin --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova plugin add cordova-instagram-plugin --save (exit code 1):
        
        Installing "cordova-instagram-plugin" for ios
        Failed to install 'cordova-instagram-plugin': Error
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:205:33
        at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
        at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
        at Promise.promise.promiseDispatch
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
        at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
        at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:73:7)
        at process._tickCallback (internal/process/next_tick.js:104:9)
        Error: Failed to fetch plugin https://github.com/Visigo/CordovaClipboard.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module`

Do you need more informations? 

`
cordova -v
7.0.1
`
`
ionic -v
3.4.0
`

Thank you

**Comment by codebeauty** [comment]
Okay, it looks like there was some cluttered stuff. Installation works fine without errors after removing all mentions of Instagram and Clipboard plugin from **package.json**, **package-lock.json**, **config.xml** and **plugins/ios.json**.
