### ISSUE TITLE
Ionic plugin wrapper causes plugin install error

### ISSUE THREAD

**Issue by rolinger** [vstirbu/InstagramPlugin#95]
Using Ionic v3.19 - it uses the new: `ionic cordova plugin add cordova-instagram-plugin` format and it gives the following error:

```
ionic cordova plugin add cordova-instagram-plugin
> cordova plugin add cordova-instagram-plugin --save
Installing "cordova-instagram-plugin" for android
Failed to install 'cordova-instagram-plugin': CordovaError: Failed to fetch plugin https://github.com/Visigo/CordovaClipboard.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rolin\AppData\Roaming\npm-cache\_logs\2018-02-17T23_20_44_877Z-debug.log
    at C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\rolin\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(node:15964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to fetch plugin https://github.com/Visigo/CordovaClipboard.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rolin\AppData\Roaming\npm-cache\_logs\2018-02-17T23_20_44_877Z-debug.log


```

Just using the standard `cordova plugin install cordova-instagram-plugin` installed without error.

**Comment by futuravis** [comment]
I am also facing the same issue.

**Comment by rodrigograca31** [comment]
Seems to be related to the clipboard plugin which I just changed to `cordova-clipboard`

This should be fixed. Closing
